<?php
/**
 * @file fqc.module
 */

/**
 * Implements hook_help().
 */
function fqc_help($path, $arg) {
  switch ($path) {
    case 'admin/help#fqc':
      return '<p>' . t('Perform a federated query on multiple RDF data sources by caching data locally from designated SPARQL endpoints.') . '</p>';
    break;

    case 'admin/structure/fqc':
      $endpoint = url('sparql', array('absolute' => TRUE,));
      $registry = l('SPARQL Endpoints Registry', 'admin/structure/sparql_registry');
      return '<p>' . t("This page enables RDF administrators to designate SPARQL endpoints to be cached locally for federated queries. Cached data can be queried with SPARQL queries against the local endpoint: !endpoint. Note: Your local endpoint must be registered with the !registry, otherwise it won't work.",
      array('!endpoint' => l($endpoint, $endpoint), '!registry' => $registry)
      ) . '</p>';
    break;
  }
}

/**
 * Implements hook_menu().
 */
function fqc_menu() {
  $items = array();

  $items['admin/structure/fqc'] = array(
    'title' => 'Federated Query Cache',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('fqc_admin_structure'),
    'description' => 'Cache RDF data from designated SPARQL endpoints locally.',
    'access arguments' => array('administer rdf'),
    'file' => 'fqc.admin.inc',
    'weight' => 1,
  );

  return $items;
}

/**
 *
 */
function fqc_get_data() {
  // Instantiate the ARC2 local store.
  $store = sparql_endpoint_initialize();

  // Emtpy the local store.
  $store->reset();

  // Load data.
  $endpoints = variable_get('fqc_endpoints', NULL);
  $domains = explode("\n", $endpoints);
  foreach ($domains as $domain) {
    $domain = trim($domain);
    if (strlen($domain)) {
      $q = 'LOAD <' . $domain . '?query=CONSTRUCT+{%0D%0A++%3Fs+%3Fp+%3Fo%0D%0A}+WHERE+{%3Fs+%3Fp+%3Fo+.}&output=&jsonp=&key=>';
      $store->query($q);
    }
  }


  if ($store->getErrors()) {
    drupal_set_message(t('There was an error during the fetching of the data.'), 'error');
  }
  else {
    drupal_set_message(t('Cached federated query data has been refreshed. Click !url to review data.', array(
      '!url' => l('here', 'sparql', array(
        'query' => array(
          'query' => 'SELECT * WHERE {?s ?p ?o}',
          'output' => 'htmltab',
        ),
      )),
    )));
  }
}
